name: Релиз проекта keycloak-russian-providers
on:
  release:
    types: [published]
jobs:
  build-master:
    name: Релиз проекта
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование проекта
        uses: actions/checkout@v4  # Checkout the repository code
      - name: Установка Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Публикация проекта в Maven Central
        run: |
          cat <(echo -e "${{ secrets.MAVEN_GPG_PRIVATE_KEY }}") | gpg --batch --import
          ./mvnw versions:set -DnewVersion=$GITHUB_REF_NAME        
          ./mvnw --no-transfer-progress --batch-mode -Dgpg.passphrase=${{ secrets.MAVEN_GPG_PASSPHRASE }} -Dgpg.keyname=C9AAFE214609D9C5 verify gpg:sign install:install deploy:deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}